### ISSUE TITLE
Make 'uwu' localizeable

### ISSUE THREAD

**Issue by UpcraftLP** [quat1024/uwu_mod#6]
Currently you substitute the language map with one that hardcodes `uwu` as replacement, what about making it pull from a lang file instead, so you can translate `uwu`?

**Comment by thetakodev** [comment]
There is a better option. Make localization of uwu random!
On startup it will choose a localization:
- uwu
- owo
etc

**Comment by UpcraftLP** [comment]
> There is a better option. Make localization of uwu random!
> On startup it will choose a localization:
> 
> * uwu
> * owo
>   etc

that is not how localization works..

**Comment by quat1024** [comment]
yall this isn't owo mod
